# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SAMPLE_RUST_MINIMAL)		+= rust_minimal.o
obj-$(CONFIG_SAMPLE_RUST_PRINT)			+= rust_print.o
obj-$(CONFIG_SAMPLE_RUST_FS)                    += rust_fs.o
obj-$(CONFIG_SAMPLE_RUST_SELFTESTS)             += rust_selftests.o
obj-$(CONFIG_SAMPLE_RUST_HELLO_WORLD)	        += rust_helloworld.o
subdir-$(CONFIG_SAMPLE_RUST_HOSTPROGS)		+= hostprogs
